throw a helpful error message if subcommand does not exist

diff --git a/bin/ide b/bin/ide
--- a/bin/ide
+++ b/bin/ide
@@ -7,5 +7,11 @@ export IDE_PATH=$(dirname $(dirname "${BASH_SOURCE[0]}"))
 COMMAND=${1-help}
 shift
 
+if [ ! -f "$IDE_PATH/exec/$COMMAND" ]
+then
+    echo "ERROR: subcommand $COMMAND does not exist" > /dev/stderr
+    exit 1
+fi
+
 # Execute the subcommand
 exec "$IDE_PATH/exec/$COMMAND" "$@"
